// generated by stringer -type=Op; DO NOT EDIT

package watcher

import "fmt"

const (
	_Op_name_0 = "Create"
	_Op_name_1 = "Write"
	_Op_name_2 = "Remove"
	_Op_name_3 = "Rename"
	_Op_name_4 = "Chmod"
)

var (
	_Op_index_0 = [...]uint8{6}
	_Op_index_1 = [...]uint8{5}
	_Op_index_2 = [...]uint8{6}
	_Op_index_3 = [...]uint8{6}
	_Op_index_4 = [...]uint8{5}
)

func (i Op) String() string {
	switch {
	case i == 0:
		return _Op_name_0
	case i == 2:
		return _Op_name_1
	case i == 4:
		return _Op_name_2
	case i == 6:
		return _Op_name_3
	case i == 8:
		return _Op_name_4
	default:
		return fmt.Sprintf("Op(%d)", i)
	}
}
